<?php
require_once __DIR__ . '/../../functions/auth.php';
require_once __DIR__ . '../../../helper/route.php';
checkAuth();
?>

<!DOCTYPE html>
<html lang="id">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Services Section - ESTU CMS</title>
    <link href="https://fonts.googleapis.com/css2?family=Inter:wght@300;400;500;600;700&display=swap" rel="stylesheet">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.4.0/css/all.min.css">
    <link rel="stylesheet" href="<?= asset('css/toast.css') ?>">
    <link rel="stylesheet" href="<?= asset('css/service/main.css') ?>">
</head>
<body>
    <div class="dashboard">
        <?php require_once __DIR__ . '/../dashboard/sidebar.php'; ?>

        <main class="main-content">
            <header class="header">
                <div class="search-box">
                    <i class="fas fa-search"></i>
                    <input type="text" placeholder="Cari..." id="searchInput">
                </div>

                <div class="header-actions">
                    <div class="notification-wrapper">
                        <button class="icon-btn" id="notificationBtn">
                            <i class="fas fa-bell"></i>
                            <span class="notification-dot" id="notificationDot"></span>
                        </button>
                        <div class="notification-dropdown" id="notificationDropdown">
                            <div class="notification-header">
                                <h4>Notifikasi</h4>
                                <button class="mark-all-read" id="markAllRead">Tandai sudah dibaca</button>
                            </div>
                            <div class="notification-list" id="notificationList"></div>
                        </div>
                    </div>
                </div>
            </header>

            <div class="content">
                <!-- Page Header -->
                <div class="page-header">
                    <div class="page-header-left">
                        <h1 class="page-title">Services Section</h1>
                        <p class="page-subtitle">Kelola konten layanan yang ditampilkan pada halaman utama.</p>
                    </div>
                </div>

                <!-- Live Preview -->
                <div class="services-preview-section" id="servicesPreviewSection">
                    <div class="services-preview-header-inline">
                        <h3><i class="fas fa-eye"></i> Live Preview</h3>
                        <span class="preview-badge">Real-time</span>
                    </div>
                    <div class="services-preview-content">
                        <!-- Header Preview -->
                        <div class="text-center mb-16">
                            <span class="preview-section-label" id="previewSectionLabel">Our Services</span>
                            <h2 class="preview-section-title" id="previewSectionTitle">INTEGRATED EVENT<br>SOLUTIONS</h2>
                            <p class="preview-section-desc" id="previewSectionDesc">End-to-end event organizer Bali services ensuring every detail of your event is perfect.</p>
                        </div>
                        
                        <!-- Services Grid Preview -->
                        <div class="services-preview-grid" id="servicesPreviewGrid">
                            <!-- Generated by JS -->
                        </div>
                    </div>
                </div>

                <!-- Form Container -->
                <div class="form-container">

                    <!-- Section Header Settings -->
                    <div class="form-card">
                        <div class="form-card-header">
                            <div class="form-card-icon">
                                <i class="fas fa-heading"></i>
                            </div>
                            <div class="form-card-title">
                                <h3>Header Section</h3>
                                <p>Label, judul dan deskripsi section</p>
                            </div>
                        </div>
                        <div class="form-card-body">
                            <div class="form-row">
                                <div class="form-group">
                                    <label>Judul Baris 1</label>
                                    <input type="text" class="form-control" id="titleLine1" value="INTEGRATED EVENT" placeholder="Baris pertama judul" oninput="updatePreview()">
                                </div>
                                <div class="form-group">
                                    <label>Judul Baris 2</label>
                                    <input type="text" class="form-control" id="titleLine2" value="SOLUTIONS" placeholder="Baris kedua judul" oninput="updatePreview()">
                                </div>
                            </div>

                            <div class="form-group mt-4">
                                <label>Deskripsi Section</label>
                                <div class="rich-editor-container">
                                    <div class="rich-editor-toolbar">
                                        <button type="button" class="rte-btn" data-command="bold" title="Bold (Ctrl+B)">
                                            <i class="fas fa-bold"></i>
                                        </button>
                                        <button type="button" class="rte-btn" data-command="italic" title="Italic (Ctrl+I)">
                                            <i class="fas fa-italic"></i>
                                        </button>
                                        <button type="button" class="rte-btn" data-command="removeFormat" title="Clear Format">
                                            <i class="fas fa-remove-format"></i>
                                        </button>
                                    </div>
                                    <div class="rich-editor" id="sectionDesc" contenteditable="true" oninput="updatePreview()">
                                        End-to-end event organizer Bali services ensuring every detail of your event is perfect.
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>

                    <!-- Services Management -->
                    <div class="form-card">
                        <div class="form-card-header">
                            <div class="form-card-icon">
                                <i class="fas fa-th-large"></i>
                            </div>
                            <div class="form-card-title">
                                <h3>Kelola Layanan</h3>
                                <p>Tambah, edit, atau hapus layanan</p>
                            </div>
                            <button type="button" class="btn-add-service" onclick="addNewService()">
                                <i class="fas fa-plus"></i> Tambah Layanan
                            </button>
                        </div>
                        <div class="form-card-body">
                            <div class="services-form-list" id="servicesFormList">
                                <!-- Service items generated by JS -->
                            </div>
                        </div>
                    </div>

                </div>

                <!-- Tombol Simpan Perubahan -->
                <div class="save-section">
                    <button class="btn-save-bottom" onclick="saveServicesData()">
                        <i class="fas fa-save"></i> Simpan Perubahan
                    </button>
                </div>

            </div>
        </main>
    </div>

    <!-- Toast -->
    <div class="toast" id="toast">
        <div class="toast-icon" id="toastIcon">
            <i class="fas fa-check"></i>
        </div>
        <div class="toast-content">
            <h4 id="toastTitle">Berhasil</h4>
            <p id="toastMessage">Data berhasil disimpan</p>
        </div>
    </div>

    <script src="<?= asset('js/service/main.js') ?>"></script>
</body>
</html>